package catan;// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/************************************************************/
/**
 * Extends Build to implement process for building roads
 * 
 * @author Nina Hay Cooper
 * 
 *         February 13th 2026
 */
public class BuildRoad extends Build {
	/**
	 * Constructor
	 *
	 * @param player             Player who is building the road
	 * @param board              the board game
	 * @param randomizer         randomizer object
	 * @param placementValidator placement generator
	 */
	public BuildRoad(Player player, Board board, Randomizer randomizer,Bank bank, PlacementValidator placementValidator) {
		super(player, board, randomizer, bank, placementValidator);

	}

	/**
	 * Checking that the player has the resources to buy the road and has roads left
	 * 
	 */
	@Override
	protected boolean canPlayerBuy() {
		boolean hasResources = player.getResourceHand().canBuyRoad();
		boolean hasRoadsLeft = player.getPlayerRoadsLeft() > 0;

		return hasResources && hasRoadsLeft;
	}

	@Override
	protected boolean hasValidPlacement(){
		//if it's not empty, two thumbs up
		return (!placementValidator.getValidRoadEdges(player).isEmpty());
	}
	@Override
	protected Object generatePlacement() {
		/*use the placement validator to get the placements*/
		List<Edge> validEdges = placementValidator.getValidRoadEdges(player);
		/*if there are no valid places return null*/
		if(validEdges.isEmpty()){
			return null;
		}
		/*select a random index from the valid edges*/
		int index = randomizer.randomSelection(0, validEdges.size()-1);
		return validEdges.get(index);
	}

	// placement needs to be a pair of nodes
	@Override
	protected boolean validatePlacement(Object placement) {
		//type case edge to placement
		Edge edge = (Edge) placement;
		return placementValidator.canBuildRoad(edge, player);

	}


	/**
	 * Do the build operation, this includes: - paying for the build - updating the
	 * board - updating player info
	 * 
	 * 
	 */
	@Override
	protected void doBuild(Object placement) {
		Edge edges = (Edge) placement;

		/* Pay for the build */
		player.getResourceHand().payForRoad(bank);

		/* Create road, add it to the player and the edge */
		Road road = new Road (player.getPlayerID(),edges);
		edges.placeRoad(road);
		player.playerAddRoad(road);

	}

	/**
	 * Print Statement
	 * 
	 */
	@Override
	public void printAction(Object placement) {
		Edge edges = (Edge) placement;

		System.out.printf("[Player " + player.getPlayerID() + "] : [Built a Road between %d and %d]\n",
				edges.getNodeA().getNodeID(),
				edges.getNodeB().getNodeID());
	}

}
