// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
//
//package InItToWinIt_Team26;
//
///************************************************************/
///**
// * 
// */
//public class Bank {
//	/**
//	 * 
//	 */
//	private int lumber;
//	/**
//	 * 
//	 */
//	private int wool;
//	/**
//	 * 
//	 */
//	private int grain;
//	/**
//	 * 
//	 */
//	private int brick;
//	/**
//	 * 
//	 */
//	private int ore;
//
//	/**
//	 * 
//	 */
//	public void Bank() {
//	}
//
//	/**
//	 * 
//	 * @param lumber 
//	 * @param wool 
//	 * @param grain 
//	 * @param brick 
//	 * @param ore 
//	 * @return 
//	 */
//	public boolean hasResources(int lumber, int wool, int grain, int brick, int ore) {
//	}
//
//	/**
//	 * 
//	 * @param player 
//	 * @param lumber 
//	 * @param wool 
//	 * @param grain 
//	 * @param brick 
//	 * @param ore 
//	 * @return 
//	 */
//	public boolean transferToPlayer(Player player, int lumber, int wool, int grain, int brick, int ore) {
//	}
//
//	/**
//	 * 
//	 * @return 
//	 * @param player 
//	 * @param lumber 
//	 * @param wool 
//	 * @param grain 
//	 * @param brick 
//	 * @param ore 
//	 */
//	public boolean ReceiveFromPlayer(Player player, int lumber, int wool, int grain, int brick, int ore) {
//	}
//}

public class Bank {

    //*************************************************************************************
    //the bank begins with 19 cards of each resource
    //the bank will be stored in an array with each index representing a resource:
    //---------------------------------------------------------------
    // ---> 0 = lumber, 1 = wool, 2 = grain, 3 = brick, 4 = ore <---
    //---------------------------------------------------------------
    //*************************************************************************************

    //instance variable:
    private int[] bankResources;

    //constructor:
    public Bank() {
        bankResources = new int[]{19, 19, 19, 19, 19};

    }


    //name the resources so they can be referenced by name and not index
    private String resourceName(int resourceType) {

        if (resourceType == 0) {
            return "Lumber";

        } else if (resourceType == 1) {
            return "Wool";

        } else if (resourceType == 2) {
            return "Grain";

        } else if (resourceType == 3) {
            return "Brick";

        } else if (resourceType == 4) {
            return "Ore";
        } else {
            return "ERROR: Resource type does not exist in this bank";
        }

    }


    //alot of prints are for test cases
    //check that there are enough resources in the bank to be distributed to the player
    //also update the amount of cards left after distributing
    public boolean hasResources(int resourceType, int amountWithdrawal) {

        int amountOfResource = bankResources[resourceType]; //check how many cards of THIS resource is in the bank

        String name = resourceName(resourceType);  //get the name of the resource

        if (amountOfResource <= 0) {
            System.out.println("The bank no longer contains " + name);
            return false;

        } else if (amountWithdrawal > amountOfResource) {
            System.out.println("The bank doesn't have " + amountWithdrawal + "cards, so you can only receive " + amountOfResource);
            return true;    //allows distrib to happen

        } else {    //if amountWithdrawal <= amountOfResource
            System.out.println("You have received " + amountWithdrawal + " " + name + " cards");
            return true;    //allows distrib to happen
        }


    }


    //this if the amount of card in the bank after they're distributed to players
    public void transferToPlayer(int resourceType, int amountWithdrawal) {

        int amountOfResource = bankResources[resourceType]; //check how many cards of THIS resource is in the bank


        if (hasResources(resourceType, amountWithdrawal)) {  //check that theres enough in bank currently

            if (amountWithdrawal > amountOfResource) {
                bankResources[resourceType] = 0;

            } else  {

                //if yes.. update amount of cards
                bankResources[resourceType] -= amountWithdrawal;
            }


        } else {
            System.out.println("i think an arror has occured");
        }

    }



    //this method just increase the amount of a resource in the bank when they are spent
    public void resourceDeposit(int resourceType, int amountDeposit) {

        bankResources[resourceType] += amountDeposit;
        String resourceName = resourceName(resourceType);
        System.out.println("The bank received " + amountDeposit + " " + resourceName);

    }

    //getter, only if something outside the bank needs to know how much of a resource is in the bank
    public int getResourceAmount(int resourceType) {
        return bankResources[resourceType];
    }



    //for debugging... you can make a method to show you contents of the bank
    public void showResources() {
        System.out.println("===Bank Resources===");
        for (int i = 0; i < 5; i++) {
            System.out.println(resourceName(i) + ": " + bankResources[i]);

        }
    }

}
