// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Bank {
	/**
	 * 
	 */
	private int lumber;
	/**
	 * 
	 */
	private int wool;
	/**
	 * 
	 */
	private int grain;
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int ore;

	/**
	 * 
	 */
	public void Bank() {
	}

	/**
	 * 
	 * @param lumber 
	 * @param wool 
	 * @param grain 
	 * @param brick 
	 * @param ore 
	 * @return 
	 */
	public boolean hasResources(int lumber, int wool, int grain, int brick, int ore) {
	}

	/**
	 * 
	 * @param player 
	 * @param lumber 
	 * @param wool 
	 * @param grain 
	 * @param brick 
	 * @param ore 
	 * @return 
	 */
	public boolean transferToPlayer(Player player, int lumber, int wool, int grain, int brick, int ore) {
	}

	/**
	 * 
	 * @return 
	 * @param player 
	 * @param lumber 
	 * @param wool 
	 * @param grain 
	 * @param brick 
	 * @param ore 
	 */
	public boolean ReceiveFromPlayer(Player player, int lumber, int wool, int grain, int brick, int ore) {
	}
}
