// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public abstract class Build {
	/**
	 * 
	 */
	private Player player;

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	protected boolean checkPlayer(Player player) {
	}

	/**
	 * 
	 * @param random 
	 * @param nodeID 
	 * @return 
	 */
	protected Node generatePlacement(Randomizer random, Node nodeID) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	protected boolean checkPlacement(Node node) {
	}

	/**
	 * 
	 * @param buildMaterials 
	 */
	protected void updatePlayerInventory(Player buildMaterials) {
	}

	/**
	 * 
	 */
	public void printAction() {
	}

	/**
	 * 
	 * @param nodeID 
	 */
	protected void storeBuildLocation(Node nodeID) {
	}

	/**
	 * 
	 * @param player 
	 */
	public void execute(Player player) {
	}
}
