// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 *BuildCity handles the logic for upgrading an existing
 * settlement into a city.
 * BuildCity is responsible to check if the player can afford a city,
 * choose a valid settlement place to upgrade,
 * validate that the settlement belongs to the player, and
 * deduct resources and replace settlement with a city
 *
 * @author Serene Abou Sharaf
 *
 * February 10, 2026
 *
 */
public class BuildCity extends Build {


    /**
     * Constructor for BuildCity
     *
     * @param player     : the player performing the build
     * @param board      : the game board where build happens
     * @param randomizer : is used to randomly select placements
     */
    public BuildCity(Player player, Board board, Randomizer randomizer) {

        super(player, board, randomizer);
    }


    /**
     * Checks whether the player is allowed to buy a city
     * The conditions are that the player must have enough resources and
     * the player must still have cities left in inventory
     *
     * @return true if the player can buy a city
     */
    @Override
    protected boolean canPlayerBuy() {

        return player.getResourceHand().canBuyCity() && player.getPlayerCitiesLeft() > 0;
    }


    /**
     * Selects which settlement will be upgraded
     * If the player has no settlements, they can't upgrade
     * Otherwise, the program will randomly pick one of the player's settlements
     *
     * @return a settlement chosen for upgrade, or null if none exist
     */
    @Override
    protected Object generatePlacement() {

        //No settlements means that the player can't buy a city
        if (player.getPlayerSettlements().isEmpty()) {
            return null;
        }

        //randomly selects one settlement
        int i = randomizer.randomSelection(0, player.getPlayerSettlements().size() - 1);

        //return the chosen settlement
        return player.getPlayerSettlements().get(i);
    }


    /**
     * Validates that the chosen settlement can be upgraded
     * To do this validatePlacement must check that the settlement belongs
     * to the player.
     *
     * @param placement : the chosen settlement
     * @return true if valid
     */
    @Override
    protected boolean validatePlacement(Object placement) {


        Settlement settlement = (Settlement) placement;

        return settlement.getOwner() == player.getPlayerID(); //ensure that the player own this settlement


    }


    /**
     * Performs the actual upgrade from settlement to city
     * To do this doBuild:
     * 1. Deducts city resources
     * 2. Creates a new city
     * 3. Places a city on the node
     * 4. Updates the player's inventory
     *
     * @param placement : the settlement being upgraded
     */
    @Override
    protected void doBuild(Object placement) {


        Settlement oldSettlement = (Settlement) placement;
        Node node = oldSettlement.getNode();

        player.getResourceHand().payForCity(); //pays required resources

        City city = new City(node, player.getPlayerID()); //creates a city on the same node

        node.placeCity(city); //replaces settlement with city

        player.playerUpgradeToCity(oldSettlement, city); //updates the players resources (removes settlement, adds a city)


    }


    /**
     * Prints a message describing the build action
     *
     * @param placement : the settlement was upgraded
     */
    @Override
    public void printAction(Object placement) {

        Settlement settlement = (Settlement) placement;

        System.out.println("Player " + player.getPlayerID() + " upgraded node " + settlement.getNode().getNodeID() + " to a city");

    }


}