// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public abstract class Build {
	protected Player player;
	protected Board board;
	protected Randomizer randomizer;

	public Build(Player player, Board board, Randomizer randomizer){
		
		this.player=player;
		this.board=board;
		this.randomizer=randomizer;
	}

	/*General structure, final so it can't be overridden */
	public abstract boolean execute();


	/** To check if the player has the resources and if the still have the build inventory left
	 * 
	 * 
	 */
	protected abstract boolean canPlayerBuy();

	/**
	 * 
	 * Changed it to object because I realized roads use two nodes so maybe this is better. Top top level instead of node
	 * 
	 */
	protected abstract Object generatePlacement();

	/*So if I changed check to validated, I think it sounds better but sorry! */
	/**
	 * Validate that the placement works with the game rules
	 * I was thinking of board validating but I think thats too much on Synthia
	 * @param placement
	 * @return
	 */
	protected abstract boolean validatePlacement(Object placement);

	/**Do the build operation, this includes:
	 * 	- paying for the build
	 * 	- updating the board
	 * 	- updating player info
	 * 
	 * @param placement
	 */
	protected abstract void doBuild(Object placement);

	/**
	 * Print statement
	 */
	public abstract void printAction(Object placement);

}
