// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class DistributeResources {
	/**
	 * 
	 */
	private EEList tiles;

	/**
	 * 
	 * @param players 
	 * @param board 
	 */
	private void distributeResources(EEList players, Board board) {
	}
}
