// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int maxTurns;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private EEList players;
	/**
	 * 
	 */
	private int currentTurn;
	/**
	 * 
	 */
	private Bank bank;
	/**
	 * 
	 */
	private Randomizer random;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public Player player;
	/**
	 * 
	 */
	public Bank bank;
	/**
	 * 
	 */
	public Randomizer randomizer;

	/**
	 * 
	 */
	public void startGame() {
	}

	/**
	 * 
	 */
	public void checkTermination() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void takeTurn(Player player) {
	}

	/**
	 * 
	 */
	public void Game() {
	}
}
