// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeID;
	/**
	 * 
	 */
	private int adjacentMat[];
	/**
	 * 
	 */
	private int occupencyMat[];

	/**
	 * 
	 * @param adjacentMat 
	 * @return 
	 */
	public boolean isAdjacent(int adjacentMat) {
	}

	/**
	 * 
	 * @param occupencyMat 
	 * @param return 
	 */
	public void isOccupied(int occupencyMat, boolean return) {
	}

	/**
	 * 
	 * @param player 
	 * @param building 
	 */
	private void placeBuilding(Player player, Build building) {
	}

	/**
	 * 
	 * @param building 
	 */
	public void getBuilding(Build building) {
	}
}
