// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Player {
	private int playerID;
	private int victoryPoints;
	private ResourceHand resourceHand;

	/*Player Build Capacities */
	//
	private static final int maxRoads = 15;
	private static final int maxSettlements = 5;
	private static final int maxCities = 4;
	
	/*Track the Players Builds */
	private List<Road> playerRoads;
	private List<Settlement> playerSettlements;
	private List<City> playerCities;

	/*Constructor */
	public Player(int playerID){
		this.playerID=playerID;
		this.victoryPoints=2;
		this.resourceHand= new ResourceHand();
		this.playerRoads= new ArrayList<>();
		this.playerSettlements= new ArrayList<>();
		this.playerCities= new ArrayList<>();
	}

	/*Getters for player board buildings */
	public List<Road> getPlayerRoads(){
		return playerRoads;
	}
	public List<Settlement> getPlayerSettlements(){
		return playerSettlements;
	}

	public List<City> getPlayerCities(){
		return playerCities;
	}

	/**Get the build supplies, buildings not used yet 
	 * The max - their current number
	 */

	public int getPlayerRoadsLeft(){
		//Need to verify size edge cases for when there's nothing in there 
		return maxRoads-playerRoads.size();//size is the number of elements
	}

	public int getPlayerSettlementsLeft(){
		return maxSettlements-playerSettlements.size();
	}

	public int getPlayerCitiesLeft(){
		return maxCities-playerCities.size();
	}
	
	/*---Adding the build to the player, not to the board---*/
	public void playerAddRoad(Road road){
		if(getPlayerRoadsLeft()<=0){
			throw new IllegalStateException("Error: The player has no roads left");
		}
		playerRoads.add(road);
		//not including victory points
	}

	public void playerAddSettlement(Settlement settlement){
		if(getPlayerSettlementsLeft()<=0){
			throw new IllegalStateException("Error: The player has no settlements left");
		}
		playerSettlements.add(settlement);
		
		victoryPoints += 1;
	}
	
	//

	/** Dealing with adding a city and removing the settlement
	 * nodeID of the settlement being removed
	 */
	public void playerUpgradeToCity(Settlement settlementBeingUpgraded, City cityPlaced){//maybe just an int rather than settlement
		if(getPlayerCitiesLeft()<=0){
			throw new IllegalStateException("Error: The player has no cities left");
		}

		//check if settlement is valid and also remove it, could do it more explicitly 
		if(!playerSettlements.remove(settlementBeingUpgraded)){//if there was no settlement to remove
			throw new IllegalArgumentException("Error: No settlement to be upgraded there");
		}//since the max is size based this also puts it back in store

		/*add city for player */
		playerCities.add(cityPlaced);

		victoryPoints += 2;

	}

	/*Msc Getters I need to check if we need */
	public int getPlayerID(){
		return playerID;
	}

	public int getVictoryPoints(){
		return victoryPoints;
	}
	public ResourceHand getResourceHand(){
		return resourceHand;
	}
	
}
