// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class VictoryPointConditions {
				/**
				 * 
				 */
				private undef player : Player;
				/**
				 * 
				 */
				private undef board : Board;
	/**
	 * 
	 * @param player 
	 * @param board 
	 */
	public void VictoryPointCheck(Player player, Board board) {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean didPlayerBuildSettlement() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean didPlayerBuildCity() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkLongestRoad() {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateVictoryPoints() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkWinConditions() {
	}
}
