package main.java;// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/************************************************************/
/**
 * Extends Build to implement process for building roads
 * 
 * @author Nina Hay Cooper
 * 
 *         February 13th 2026
 */
public class BuildRoad extends Build {
	/**
	 * Constructor
	 *
	 * @param player             Player who is building the road
	 * @param board              the board game
	 * @param randomizer         randomizer object
	 * @param placementValidator placement generator
	 */
	public BuildRoad(Player player, Board board, Randomizer randomizer,Bank bank, PlacementValidator placementValidator) {
		super(player, board, randomizer, bank, placementValidator);

	}

	/**
	 * Checking that the player has the resources to buy the road and has roads left
	 * 
	 */
	@Override
	protected boolean canPlayerBuy() {
		boolean hasResources = player.getResourceHand().canBuyRoad();
		boolean hasRoadsLeft = player.getPlayerRoadsLeft() > 0;

		return hasResources && hasRoadsLeft;
	}

	protected boolean hasValidPlacements(){
	}
	@Override
	protected Object generatePlacement() {
		// To hold all the possible valid placements of the road
		List<Edge> validPlacements = new ArrayList<>();

		// want to store all the nodes that are connected but not double coount
		Set<Integer> connectedPlayerNodeIDs = new HashSet<>();

		// looping through player roads
		for (Road road : player.getPlayerRoads()) {
			// adding both nodes from the player's roads to the set
			connectedPlayerNodeIDs.add(road.getNodeA().getNodeID());
			connectedPlayerNodeIDs.add(road.getNodeB().getNodeID());
		}

		// Add node IDs from settlements
		for (Settlement settlement : player.getPlayerSettlements()) {
			connectedPlayerNodeIDs.add(settlement.getNode().getNodeID());
		}

		for (City city : player.getPlayerCities()) {
			connectedPlayerNodeIDs.add(city.getNode().getNodeID());
		}

		// put the connected nodes to valid placements
		for (Integer nodeID : connectedPlayerNodeIDs) {
			List<Integer> adjacentNodeIDs = board.getAdjacentEdges(nodeID);

			// for each loop using the singular id
			for (Integer adjacentID : adjacentNodeIDs) {
				// check that the board doesn't have a road between there
				if (!(board.hasRoad(nodeID, adjacentID))) {
					// to the node id
					validPlacements.add(new Edge(nodeID, adjacentID));// this is now a valid placement
				}

			}

		}

		// no valid placements
		if (validPlacements.isEmpty()) {
			return null;
		}
		// randomize is inclusive so I need to subtract 1
		int randomizedIndex = randomizer.randomSelection(0, validPlacements.size() - 1);// random index

		return validPlacements.get(randomizedIndex);

	}

	// placement needs to be a pair of nodes
	@Override
	protected boolean validatePlacement(Object placement) {
		// casting the node to the
		Edge edges = (Edge) placement;
		int nodeToID = edges.getNodeToID();
		int nodeFromID = edges.getNodeFromID();

		// check if they're adjacent
		if (!board.isAdjacent(nodeToID, nodeFromID)) {
			return false;// not adjacent

		}

		if (board.hasRoad(nodeFromID, nodeToID)) {
			return false;// road already there
		}

		// check if connected
		boolean nodeToConnected = isNodeConnectedToPlayer(nodeToID);
		boolean nodeFromConnected = isNodeConnectedToPlayer(nodeFromID);

		// true based on if either node is connected
		return (nodeToConnected || nodeFromConnected);

	}


	/**
	 * Do the build operation, this includes: - paying for the build - updating the
	 * board - updating player info
	 * 
	 * 
	 */
	@Override
	protected void doBuild(Object placement) {
		Edge edges = (Edge) placement;

		// didn't like the naming of to and from but now it's inconsistent
		int nodeToID = edges.getNodeToID();
		int nodeFromID = edges.getNodeFromID();

		/* Pay for the build */
		player.getResourceHand().payForRoad(bank);

		/* Create road */
		// I NEED to get the node objects from board
		Road newRoad = board.placeRoad(nodeFromID, nodeToID, player.getPlayerID());

		// adding it to the player
		player.playerAddRoad(newRoad);

	}

	/**
	 * Print Statement
	 * 
	 */
	@Override
	public void printAction(Object placement) {
		Edge edges = (Edge) placement;
		int node1ID = edges.getNodeToID();
		int node2ID = edges.getNodeFromID();

		System.out.printf("[Player " + player.getPlayerID() + "] : [Built a Road between %d and %d]\n", node1ID,
				node2ID);
	}

}
