package main.java;// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * Class for the player object
 * 
 * @author Nina Hay Cooper
 * 
 *         February 13th 2026
 * 
 */
public class Player {
	private final int playerID;//player ID doesn't change
	private int victoryPoints;
	private final ResourceHand resourceHand;//their resource hand doesn't change

	/* Player Build Capacities */
	private static final int maxRoads = 15;
	private static final int maxSettlements = 5;
	private static final int maxCities = 4;

	/* Track the Players Builds */
	private final List<Road> playerRoads;
	private final List<Settlement> playerSettlements;
	private final List<City> playerCities;

	/**
	 * Constructor
	 * 
	 * @param playerID player ID from game
	 */
	public Player(int playerID) {
		this.playerID = playerID;
		this.victoryPoints = 0;
		this.resourceHand = new ResourceHand();
		this.playerRoads = new ArrayList<>();
		this.playerSettlements = new ArrayList<>();
		this.playerCities = new ArrayList<>();
	}

	/* Getters for player board buildings */
	public List<Road> getPlayerRoads() {
		return playerRoads;
	}

	public List<Settlement> getPlayerSettlements() {
		return playerSettlements;
	}

	public List<City> getPlayerCities() {
		return playerCities;
	}

	/**
	 * Get the build supplies, buildings not used yet The max - their current number
	 */

	public int getPlayerRoadsLeft() {
		// Need to verify size edge cases for when there's nothing in there
		return maxRoads - playerRoads.size();// size is the number of elements
	}

	public int getPlayerSettlementsLeft() {
		return maxSettlements - playerSettlements.size();
	}

	public int getPlayerCitiesLeft() {
		return maxCities - playerCities.size();
	}

	/* get playerID */
	public int getPlayerID() {
		return playerID;
	}
	/* get player resource hand */
	public ResourceHand getResourceHand() {
		return resourceHand;
	}

	/*---Adding the builds to the player, not to the board---*/
	/**
	 * Add road to player
	 * 
	 * @param road road being added
	 */
	public void playerAddRoad(Road road) {
		if (getPlayerRoadsLeft() <= 0) {
			throw new IllegalStateException("Error: The player "+playerID+ " has no roads left");
		}
		playerRoads.add(road);

	}

	/**
	 * Add settlement to player
	 * 
	 * @param settlement settlement being added
	 */
	public void playerAddSettlement(Settlement settlement) {
		if (getPlayerSettlementsLeft() <= 0) {
			throw new IllegalStateException("Error: The player "+ playerID+ " has no settlements left");
		}
		playerSettlements.add(settlement);
	}

	/**
	 * Records upgrading to a city for a player
	 * 
	 * @param settlementBeingUpgraded the settlement that is being removed
	 * @param cityPlaced              the city being placed
	 */
	public void playerUpgradeToCity(Node targetNodeId, City cityPlaced) {
		//if the player has no cities left to place
		if (getPlayerCitiesLeft() <= 0) {
			throw new IllegalStateException("Error: The player "+playerID+ " has no cities left");
		}
		/*initialize variable to store the settlement we want to remove, if it exists. Using the nodeID prevents the
		weaker object comparing*/
		Settlement settlementToRemove = null;
		/*search for the settlement on the target nodeID (again, if it exists)*/
		for (Settlement s : playerSettlements) {
			//if we get a match, break out of the loop
			if(s.getNode()==targetNodeId){
				settlementToRemove = s;
				break;
			}
		}
		/*if after looking it's still null*/
		if (settlementToRemove == null) {
			throw new IllegalArgumentException("Error: player "+playerID+" has no settlement at Node "+targetNodeId+
					"to upgrade");
		}
		/* Otherwise, remove settlement and add city for player */
		playerSettlements.remove(settlementToRemove);
		playerCities.add(cityPlaced);

	}



}
