// --------------------------------------------------------
// Code generated by Papyrus Java
// -------------------------------------------------------

/************************************************************/
/**
 * Build Abstract Class to Implement the different build types
 * 
 * @author Nina Hay Cooper February 13th 2026
 */
public abstract class Build {
	//
	protected Player player;
	protected Board board;
	protected Randomizer randomizer;

	/**
	 * Constructor for Build
	 * 
	 * @param player     player that is building
	 * @param board      the board where the build is happening
	 * @param randomizer that randomizes that placements
	 */
	public Build(Player player, Board board, Randomizer randomizer) {
		this.player = player;
		this.board = board;
		this.randomizer = randomizer;
	}

	/**
	 * General structure for build First: check if the player can buy the building
	 * type Second: generate a build placement Third: validate the build placement
	 * Fourth: do the actual build action Fifth: Print Action
	 * 
	 * @return
	 */
	public boolean execute() {
		/* Check if the player has the resources to build */
		if (!canPlayerBuy()) {
			return false;
		}

		/* Generate the placements */
		// Object reference for any class
		Object placement = generatePlacement();
		/* No valid placement */
		if (placement == null) {
			return false;
		}

		/* Validate Placement using Board Rules */
		if (!validatePlacement(placement)) {
			return false;// if no good
		}

		/* Buildddd */
		doBuild(placement);// okay I think this name reflects how tired I am, doBuild in retrospect doesn't
							// sound right

		/* Print statement */
		printAction(placement);

		/* If we got here, then all good */
		return true;

	}

	/**
	 * To check if the player has the resources and if the still have the build
	 * inventory left
	 * 
	 * @return true if the player is able to buy the building
	 */
	protected abstract boolean canPlayerBuy();

	/**
	 * 
	 * Changed it to object because I realized roads use two nodes so maybe this is
	 * better. Top top level instead of node
	 * 
	 */
	protected abstract Object generatePlacement();

	/**
	 * Validate that the placement works with the game rules
	 * 
	 * @param placement the target location for the placement
	 * @return true if the placement is valid, false otherwise
	 */
	protected abstract boolean validatePlacement(Object placement);

	/**
	 * Do the build operation, this includes: - paying for the build - updating the
	 * board - updating player info
	 * 
	 * @param placement
	 */
	protected abstract void doBuild(Object placement);

	/**
	 * Print statement
	 */
	public abstract void printAction(Object placement);

}
