// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile tiles;
	/**
	 * 
	 */
	private Node nodes;
	/**
	 * 
	 */
	public Node[] node;
	/**
	 * 
	 */
	public Tile[] tile;

	/**
	 * 
	 */
	private void orignalMap() {
	}

	/**
	 * 
	 */
	private void updateMap() {
	}

	/**
	 * 
	 * @param tileID 
	 * @return 
	 */
	public Tile getTile(Tile tileID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public Node getNode(Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public boolean isOccupied(Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	public boolean isAdjacent(nodeID : int) : boolean(Node nodeID) {
	}
}
