// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class BuildRoad extends Build {
	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param randomizer 
	 * @param bank 
	 * @param placementValidator 
	 */
	public void BuildRoad(Player player, Board board, Randomizer randomizer, Bank bank,
			PlacementValidator placementValidator) {
	}

	/**
	 * 
	 * @return 
	 */
	protected boolean canPlayerBuy() {
	}

	/**
	 * 
	 * @return 
	 */
	protected EJavaObject generatePlacement() {
	}

	/**
	 * 
	 * @param placement 
	 * @return 
	 */
	protected boolean validatePlacement(EJavaObject placement) {
	}

	/**
	 * 
	 * @param placement 
	 */
	protected void doBuild(EJavaObject placement) {
	}

	/**
	 * 
	 * @param placement 
	 */
	public void printAction(EJavaObject placement) {
	}
}
