// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public abstract class Build {
	/**
	 * 
	 */
	protected Player player;
	/**
	 * 
	 */
	protected Board board;
	/**
	 * 
	 */
	protected Randomizer randomizer;
	/**
	 * 
	 */
	protected Bank bank;
	/**
	 * 
	 */
	protected PlacementValidator placementyValidator;

	/**
	 * 
	 * @return 
	 */
	public boolean execute() {
	}

	/**
	 * 
	 * @return 
	 */
	protected boolean canPlayerBuy() {
	}

	/**
	 * 
	 * @return 
	 */
	protected EJavaObject generatePlacement() {
	}

	/**
	 * 
	 * @param placement 
	 */
	protected void doBuild(EJavaObject placement) {
	}

	/**
	 * 
	 */
	public void printAction() {
	}

	/**
	 * 
	 * @param placement 
	 * @return 
	 */
	protected boolean validatePlacement(EJavaObject placement) {
	}

	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param randomizer 
	 * @param bank 
	 * @param placementValidator 
	 */
	public void Build(Player player, Board board, Randomizer randomizer, Bank bank,
			PlacementValidator placementValidator) {
	}

	/**
	 * 
	 * @param placement 
	 * @return 
	 */
	public boolean executeWithPlacement(EJavaObject placement) {
	}
}
