// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class BuildCity extends Build {
	/**
	 * 
	 * @param player 
	 */
	public void execute(Player player) {
	}

	/**
	 * 
	 * @param random 
	 * @param nodeID 
	 * @return 
	 */
	protected Node generatePlacement() :

	Node(Randomizer random, Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	protected boolean checkPlacement(Node nodeID) {
	}

	/**
	 * 
	 * @param player 
	 */
	protected void updatePlayerInventory(Player player) {
	}

	/**
	 * 
	 * @param node 
	 */
	protected void storeBuildLocation(Node node) {
	}

	/**
	 * 
	 */
	public void printAction() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	protected boolean checkPlayer(Player player) {
	}
}
