// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class BuildRoad extends Build {
	/**
	 * 
	 * @param playerResources 
	 * @param playerRoads 
	 * @param playerSettlements 
	 * @param playerCities 
	 */
	protected void checkPlayer(Player playerResources, Player playerRoads, Player playerSettlements,
			Player playerCities) {
	}

	/**
	 * 
	 * @param random 
	 * @param nodeID 
	 */
	protected void generatePlacement(Randomizer random, Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	protected boolean checkPlacement(Node nodeID) {
	}

	/**
	 * 
	 * @param buildMaterials 
	 */
	protected void updatePlayerInventory(Player buildMaterials) {
	}

	/**
	 * 
	 */
	public void printAction() {
	}

	/**
	 * 
	 * @param nodeID 
	 */
	protected void storeBuildLocation(Node nodeID) {
	}

	/**
	 * 
	 * @param player 
	 */
	public void execute(Player player) {
	}
}
