// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class BuildCity extends Build {
	/**
	 * 
	 * @param player 
	 * @param board 
	 * @param ranomizer 
	 * @param bank 
	 * @param placementValidator 
	 */
	public void BuildCity(Player player, Board board, Randomizer ranomizer, Bank bank,
			PlacementValidator placementValidator) {
	}

	/**
	 * 
	 * @return 
	 */
	protected Node generatePlacement() {
	}

	/**
	 * 
	 * @param placement 
	 * @return 
	 */
	protected boolean validatePlacement(EJavaObject placement) {
	}

	/**
	 * 
	 * @param player 
	 */
	protected void doBuild(Player player) {
	}

	/**
	 * 
	 * @param placement 
	 */
	protected void build(EJavaObject placement) {
	}

	/**
	 * 
	 * @param placement 
	 */
	public void printAction(EJavaObject placement) {
	}

	/**
	 * 
	 * @return 
	 */
	protected boolean canPlayerBuy() {
	}
}
