// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class BuildSettlement extends Build {
	/**
	 * 
	 */
	public interface Interface35 {
	};

	/**
	 * 
	 * @param player 
	 */
	public void execute(Player player) {
	}

	/**
	 * 
	 * @param random 
	 * @param nodeID 
	 * @return 
	 */
	protected Node generatePlacement(Randomizer random, Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 * @return 
	 */
	protected boolean checkPlacement(Node nodeID) {
	}

	/**
	 * 
	 * @param nodeID 
	 */
	protected void storeBuildLocation(Node nodeID) {
	}

	/**
	 * 
	 */
	protected void updatePlayerInventory() {
	}

	/**
	 * 
	 */
	public void printAction() {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	protected boolean checkPlayer(Player player) {
	}
}
