// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private Node nodeA;
	/**
	 * 
	 */
	private Node nodeB;
	/**
	 * 
	 */
	private Road road;
	/**
	 * 
	 */
	public Node node;

	/**
	 * 
	 * @param nodeA 
	 * @param nodeB 
	 */
	public void Edge(Node nodeA, Node nodeB) {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNodeA() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getNodeB() {
	}

	/**
	 * 
	 * @return 
	 */
	public Road getRoad() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean hasRoad() {
	}

	/**
	 * 
	 * @param road 
	 */
	public void placeRoad(Road road) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public Node getOppositeNode(Node node) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public boolean sharesNode(Node node) {
	}

	/**
	 * 
	 * @param otherEdge 
	 * @return 
	 */
	public boolean isAdjacentTo(Edge otherEdge) {
	}
}
