// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class PlacementValidator {
	/**
	 * 
	 */
	private Board board;

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @param isInitialPlacement 
	 * @return 
	 */
	public boolean canPlaceSettlement(Node node, Player player, boolean isInitialPlacement) {
	}

	/**
	 * 
	 * @param player 
	 * @param initialPlacement 
	 * @return 
	 */
	public EEList getValidSettlementPlacements(Player player, boolean initialPlacement) {
	}

	/**
	 * 
	 * @param board 
	 */
	public void PlacementValidator(Board board) {
	}

	/**
	 * 
	 * @param settlement 
	 * @param player 
	 * @return 
	 */
	public boolean canUpgradeToCity(Settlement settlement, Player player) {
	}

	/**
	 * 
	 * @param edge 
	 * @param player 
	 * @return 
	 */
	public boolean canBuildRoad(Edge edge, Player player) {
	}

	/**
	 * 
	 * @param player 
	 * @return 
	 */
	public EEList getValidRoadEdges(Player player) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	private boolean hasConnectingRoads(Node node, Player player) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	private boolean isNodeStoringForPlayer(Node node, Player player) {
	}

	/**
	 * 
	 * @param player 
	 * @param Parameter1 
	 */
	private void getNodesUsedByPlayer(Player player, Node Parameter1) {
	}
}
