// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class PlayerAction {
	/**
	 * 
	 */
	private Player player;
	/**
	 * 
	 */
	public Build build;

	/**
	 * 
	 */
	public void chooseAction() {
	}

	/**
	 * 
	 */
	public void executeAction() {
	}

	/**
	 * 
	 */
	public void updateVictoryPoints() {
	}
}
