// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int playerID;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private EMap buildMaterials;
	/**
	 * 
	 */
	private EEList playerResources;
	/**
	 * 
	 */
	private EEList playerRoads;
	/**
	 * 
	 */
	private EEList playerSettlements;
	/**
	 * 
	 */
	private EEList playerCities;
	/**
	 * 
	 */
	public resourceHand resourcehand;
}
