// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Randomizer {
	/**
	 * 
	 */
	public Randomizer random;

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
	}

	/**
	 * 
	 * @return 
	 * @param min 
	 * @param max 
	 */
	public int randomSelection(int min, int max) {
	}
}
