// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class resourceHand {
	/**
	 * 
	 */
	private int lumber;
	/**
	 * 
	 */
	private int wool;
	/**
	 * 
	 */
	private int grain;
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int ore;
	/**
	 * 
	 */
	private int roads = 15;
	/**
	 * 
	 */
	private int settlements = 5;
	/**
	 * 
	 */
	private int cities = 4;

	/**
	 * 
	 */
	public void addResource() {
	}

	/**
	 * 
	 */
	public void removeResource() {
	}

	/**
	 * 
	 */
	public void getResources() {
	}
}
