// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Robber {
	/**
	 * 
	 */
	private Tile currentTile;
	/**
	 * 
	 */
	private Randomizer random;

	/**
	 * 
	 * @param startTile 
	 */
	public void Robber(Tile startTile) {
	}

	/**
	 * 
	 * @param player 
	 * @param bank 
	 */
	public void discardHalf(Player player, Bank bank) {
	}

	/**
	 * 
	 * @param chosenTile 
	 */
	public void moveRobber(Tile chosenTile) {
	}

	/**
	 * 
	 * @param theif 
	 * @param victim 
	 */
	public void stealCard(Player theif, Player victim) {
	}

	/**
	 * 
	 * @param board 
	 * @return 
	 */
	public Tile chooseRandomTile(Board board) {
	}

	/**
	 * 
	 * @param board 
	 * @param bank 
	 * @param players 
	 * @param currentPlayer 
	 */
	public void executeSevenRoll(Board board, Bank bank, Player players, Player currentPlayer) {
	}
}
