// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	private int tileRollNum;
	/**
	 * 
	 */
	private Bank resourceType;
}
