// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class TurnManager {
	/**
	 * 
	 */
	private Player players;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private DistributeResources distributor;
	/**
	 * 
	 */
	private Randomizer randomizer;
	/**
	 * 
	 */
	private Bank bank;
	/**
	 * 
	 */
	private PlacementValidator placementValidator;
	/**
	 * 
	 */
	private Player longestRoadHolder;
	/**
	 * 
	 */
	private int longestRoadLength;
	/**
	 * 
	 */
	private Robber robber;
	/**
	 * 
	 */
	public Player player;
	/**
	 * 
	 */
	public Board board;
	/**
	 * 
	 */
	public DistributeResources distributeresources;
	/**
	 * 
	 */
	public Randomizer randomizer;
	/**
	 * 
	 */
	public Bank bank;
	/**
	 * 
	 */
	public PlacementValidator placementvalidator;
	/**
	 * 
	 */
	public Robber robber;

	/**
	 * 
	 * @param players 
	 * @param board 
	 * @param distributor 
	 * @param randomizer 
	 * @param bank 
	 * @param placementValidator 
	 * @param robber 
	 */
	public void TurnManager(Player players, Board board, DistributeResources distributor, Randomizer randomizer,
			Bank bank, PlacementValidator placementValidator, Robber robber) {
	}

	/**
	 * 
	 * @param maxRounds 
	 * @return 
	 */
	public Player executeRounds(int maxRounds) {
	}

	/**
	 * 
	 */
	private void updateLongestRoad() {
	}

	/**
	 * 
	 * @param roundNumber 
	 */
	public void printScoreBoard(int roundNumber) {
	}
}
