// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package InItToWinIt_Team26;

/************************************************************/
/**
 * 
 */
public class VictoryPointConditions {
				/**
				 * 
				 */
				private undef player : Player;
				/**
				 * 
				 */
				private undef board : Board;
	/**
	 * 
	 * @param player 
	 * @param board 
	 */
	public void VictoryPointCheck(Player player, Board board) {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean didPlayerBuildCity() {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateSettlementVP() {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateCityVP() {
	}
	/**
	 * 
	 * @return 
	 */
	public int getLongestRoad() {
	}
	/**
	 * 
	 * @return 
	 */
	private int findLongestRoad() {
	}
	/**
	 * 
	 * @param graph 
	 * @param current 
	 * @param visitedEdges 
	 */
	private void longestPath(EMap graph, int current, String visitedEdges) {
	}
	/**
	 * 
	 * @return 
	 */
	public int calculateVictoryPoints() {
	}
	/**
	 * 
	 * @return 
	 */
	public boolean checkWinConditions() {
	}
}
